default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  charset: utf8
  collation: utf8_general_ci
  username: root

development:
  <<: *default
  database: perfectter_development

test:
  <<: *default
  database: perfectter_test

production:
  <<: *default
  database: perfectter_production
